version: '3.4'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_USER=user-svc-user
      # - MYSQL_PASSWORD=user-svc-password
    entrypoint:
      sh -c "
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8 --collation-server=utf8_general_ci "
    # entrypoint:
    #   sh -c "
    #   echo 'CREATE DATABASE IF NOT EXISTS user_svc;' > /docker-entrypoint-initdb.d/init.sql;
    #   /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8 --collation-server=utf8_general_ci "

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '9090:80'
    environment:
      PMA_HOST: db

  kafka:
    container_name: kafka
    image: johnnypark/kafka-zookeeper
    environment: 
      ADVERTISED_HOST: kafka
    ports:
      - 2181:2181
      - 9092:9092

volumes:
  local-volume: