version: '3.4'

services:

  kafka:
    container_name: kafka
    image: johnnypark/kafka-zookeeper
    environment: 
      ADVERTISED_HOST: kafka
    ports:
      - 2181:2181
      - 9092:9092

  mongo-express:
      image: mongo
      # restart: always
      ports:
          - 27017:27017
      environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  local-volume: